# Generated by Django 5.2.16 on 2026-07-17 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Item URL')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Item Title')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Price')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fixed Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Check date')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.target', verbose_name='Target')),
            ],
            options={
                'verbose_name': 'Price History Log',
                'verbose_name_plural': 'Price History Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
